#!/bin/bash
#PBS -q defaultQ
#PBS -N ONT_alignment
#PBS -l select=1:ncpus=24:mem=24GB
#PBS -l walltime=150:00:00
#PBS -M zzha8134@uni.sydney.edu.au
#PBS -m abe
#PBS -P RDS-FSC-BacCock-RW

# Load software
module load samtools
module load minimap2

# Set variables
raw_seq=Z4_ONT_raw.fasta
reference_genome=Z4_flye-assembly_polished-it2_filtered.fasta 
sample=Z4-2
threads=4
working_dir=/scratch/BacCock/Genome/HGT/test

cd ${working_dir}

# Performing the alignment with minimap2
minimap2 -ax map-ont -L -t ${threads} ${reference_genome} ${raw_seq} > ${sample}_aln.sam

# Filter and sort alignment file
samtools view -Sb ${sample}_aln.sam \
	| samtools sort -n -@${threads} - \
	| samtools fixmate -m - - \
	| samtools sort -@${threads} - \
	| samtools markdup -r - ${sample}_aln-sorted.bam

# Clean original alignment
rm ${sample}_aln.sam

