#!/bin/bash
#PBS -q defaultQ
#PBS -N bwa_HGT_run
#PBS -l select=1:ncpus=8:mem=24GB
#PBS -l walltime=4:00:00
#PBS -M kyle.ewart@sydney.edu.au
#PBS -m abe
#PBS -P RDS-FSC-WholeGenomeAssembly-RW

module load bwa
module load seqkit

work=/scratch/WholeGenomeAssembly/HGT/working
genome=Blattella_germanica.genome.fa
Blatta_chunks=Blattabacterium-genomes_chunks.fasta
sample=B-germanica-v1

cd ${work}

# Index genome
bwa index ${genome}
# Perform alignment
bwa mem ${genome} ${Blatta_chunks} > ${sample}.sam

# Get contig lengths of genome
seqkit fx2tab --length --name --header-line ${genome} > ${sample}_contig-lengths.txt
